spring:
  datasource:
    url: jdbc:mariadb://localhost/foodlookup
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    
  jpa:
    properties:
      hibernate.ddl-auto: validate
      hibernate.id.db_structure_naming_strategy: single
      
  flyway:
    baseline-on-migrate: true
    out-of-order: true
    baseline-version: 0
    locations:
      - classpath:/db/migration
